<template>
  <div>
    <HeaderComponent></HeaderComponent>
    <MainSliderComponent></MainSliderComponent>
    <BuiltWithComponent></BuiltWithComponent>
    <ServicesComponent></ServicesComponent>
    <SamplesComponent></SamplesComponent>
  </div>
</template>
